platform :ios, '7.0'

pod 'AFNetworking', '2.6.3'
pod 'NYXImagesKit', '~> 2.3'
pod 'BlocksKit', '~> 2.2.0'
pod 'RegexKitLite', '~> 4.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'SDWebImage' , '3.7.3'
pod 'ReactiveCocoa', '2.4.7'
pod 'RESideMenu'
pod 'LGSideMenuController'
#pod 'GPUImage'
pod 'Masonry'
pod 'JDStatusBarNotification'
pod 'Mantle'
pod 'JSONModel'
pod 'GHMarkdownParser'
pod 'LGPlusButtonsView'
pod 'FMDB'
pod 'FMDBHelper'
pod 'JSBadgeView'
pod 'DZNEmptyDataSet'
pod 'ODRefreshControl'
pod 'FrameAccessor'