platform :ios, '7.0'

pod 'AFNetworking', '~> 2.2.0'
pod 'NYXImagesKit', '~> 2.3'
pod 'FXKeychain', '~> 1.5'
pod 'BlocksKit', '~> 2.2.0'
pod 'NSString-Hashes', '~> 1.2.1'
pod 'MWFeedParser', '~> 1.0.1'
pod 'RegexKitLite', '~> 4.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'SDWebImage' , '3.7.3'
pod 'RESideMenu'
#pod 'GPUImage'
pod 'Masonry'
pod 'JDStatusBarNotification'
pod 'Mantle'
pod 'JSONModel'